name: iOS starter workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'development'
      - 'main'
    paths:
      - '.github/workflows/ios.yml'
      - '**/*.swift'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - xcode: "14.3"
            ios: "15.1"
    steps:
    - uses: actions/checkout@v3
    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'

    # - name: Select Xcode
    #   run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    - name: Build
      run: xcodebuild clean build -scheme Moco -project Moco.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1'
   
    # - name: Test
    #   run: xcodebuild test -scheme KiwChing -project KiwChing.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'

    # - name: Build
    #   run: |
    #     xcodebuild build -scheme Petto -project Petto.xcodeproj clean build -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=No
    # - uses: sersoft-gmbh/xcodebuild-action@v2
    #   with:
    #     project: Petto.xcodeproj
    #     scheme: Petto
    #     destination: platform=iOS
    #     action: build
